"""s(CASP) subprocess integration and output parsing."""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from .models import FactState, PolicyResult


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_PROGRAM_PATH = ROOT_DIR / "scasp" / "tx_dl_assistant.pl"


class ScaspUnavailable(RuntimeError):
    """Raised when the local s(CASP) executable cannot be found."""


class ScaspExecutionError(RuntimeError):
    """Raised when s(CASP) returns an unexpected failure."""


class ScaspRunner:
    """Run the local s(CASP) policy program for a given fact state."""

    QUERIES = {
        "case_type": ("inferred_case(X)", "X", False),
        "next_question": ("next_question(X)", "X", False),
        "missing_info": ("missing_info(X)", "X", True),
        "service_modes": ("service_mode(X)", "X", True),
        "required_docs": ("required_doc(X)", "X", True),
        "likely_exams": ("likely_exam(X)", "X", True),
        "waivers": ("waiver(X)", "X", True),
        "explanations": ("explanation(X)", "X", True),
        "final_guidance": ("final_guidance(X)", "X", True),
    }

    def __init__(self, program_path: Path | str = DEFAULT_PROGRAM_PATH, executable: str = "scasp") -> None:
        self.program_path = Path(program_path)
        self.executable = executable

    def is_available(self) -> bool:
        return shutil.which(self.executable) is not None

    def run(self, facts: FactState) -> PolicyResult:
        """Serialize facts, execute s(CASP), and return a structured result."""

        if facts.age is not None and facts.age < 18:
            return underage_policy_result(facts)

        if not self.is_available():
            raise ScaspUnavailable(
                "The `scasp` executable was not found in PATH. Install s(CASP), then verify it with `scasp --version`."
            )
        if not self.program_path.exists():
            raise ScaspExecutionError(f"s(CASP) program not found: {self.program_path}")

        source = self._build_program_source(facts)
        raw: dict[str, Any] = {}

        with tempfile.NamedTemporaryFile("w", suffix=".pl", delete=True) as handle:
            handle.write(source)
            handle.flush()
            temp_path = Path(handle.name)

            result = PolicyResult()
            for key, (query, variable, many) in self.QUERIES.items():
                values, payload = self._run_query(temp_path, query, variable)
                raw[key] = payload
                setattr(result, key, values if many else (values[0] if values else None))

        result.raw = raw
        return result

    def _build_program_source(self, facts: FactState) -> str:
        policy_source = self.program_path.read_text(encoding="utf-8")
        return f"{self._facts_to_scasp(facts)}\n\n{policy_source}\n"

    def _facts_to_scasp(self, facts: FactState) -> str:
        lines = ["% Facts generated by the Python parser."]

        if facts.goal:
            lines.append(f"goal({self._atom(facts.goal)}).")
        if facts.age is not None:
            lines.append(f"age({facts.age}).")
        if facts.renewal_timing:
            lines.append(f"renewal_timing({self._atom(facts.renewal_timing)}).")
        if facts.adult_driver_education_status:
            lines.append(f"adult_driver_education_status({self._atom(facts.adult_driver_education_status)}).")

        boolean_predicates = {
            "applying_texas_license": facts.applying_texas_license,
            "new_texas_resident": facts.new_texas_resident,
            "has_out_of_state_license": facts.has_out_of_state_license,
            "out_of_state_license_valid": facts.out_of_state_license_valid,
            "out_of_state_license_unexpired": facts.out_of_state_license_unexpired,
            "out_of_state_license_expired_not_over_two_years": facts.out_of_state_license_expired_not_over_two_years,
            "out_of_state_license_expired_over_two_years": facts.out_of_state_license_expired_over_two_years,
            "has_texas_license": facts.has_texas_license,
            "front_card_changed": facts.front_card_changed,
            "name_change_requested": facts.name_change_requested,
            "address_change_requested": facts.address_change_requested,
            "license_lost_stolen_damaged": facts.license_lost_stolen_damaged,
            "license_stolen_and_fraud_used": facts.license_stolen_and_fraud_used,
            "has_identity_doc": facts.has_identity_doc,
            "has_social_security": facts.has_social_security,
            "has_texas_residency_docs": facts.has_texas_residency_docs,
            "lawful_presence_category_known": facts.lawful_presence_category_known,
            "lawful_presence_on_record": facts.lawful_presence_on_record,
            "owns_vehicle": facts.owns_vehicle,
            "has_proof_of_insurance": facts.has_proof_of_insurance,
            "has_texas_vehicle_registration": facts.has_texas_vehicle_registration,
            "has_card_number": facts.has_card_number,
            "has_date_of_birth_for_online": facts.has_date_of_birth_for_online,
            "has_last4_ssn": facts.has_last4_ssn,
            "has_audit_number": facts.has_audit_number,
            "us_citizen": facts.us_citizen,
            "ssn_on_record": facts.ssn_on_record,
            "last_renewed_in_person": facts.last_renewed_in_person,
            "license_valid_status": facts.license_valid_status,
            "no_outstanding_tickets_or_warrants": facts.no_outstanding_tickets_or_warrants,
            "health_conditions_unchanged": facts.health_conditions_unchanged,
        }
        negative_predicates = {
            "has_out_of_state_license": "-has_out_of_state_license",
            "out_of_state_license_valid": "-out_of_state_license_valid",
            "out_of_state_license_unexpired": "-out_of_state_license_unexpired",
            "has_texas_license": "-has_texas_license",
            "front_card_changed": "-front_card_changed",
            "owns_vehicle": "-owns_vehicle",
            "us_citizen": "-us_citizen",
            "ssn_on_record": "-ssn_on_record",
            "last_renewed_in_person": "-last_renewed_in_person",
            "license_valid_status": "-license_valid_status",
            "no_outstanding_tickets_or_warrants": "-no_outstanding_tickets_or_warrants",
            "health_conditions_unchanged": "-health_conditions_unchanged",
        }

        for predicate, value in boolean_predicates.items():
            if value is True:
                lines.append(f"{predicate}.")
            elif value is False and predicate in negative_predicates:
                lines.append(f"{negative_predicates[predicate]}.")

        return "\n".join(lines)

    def _run_query(self, program_path: Path, query: str, variable: str) -> tuple[list[str], dict[str, Any]]:
        command = [self.executable, "--json=-", "-n", "0", f"--query={query}", str(program_path)]
        completed = subprocess.run(command, text=True, capture_output=True, check=False, timeout=10)
        output = completed.stdout.strip()
        if completed.returncode != 0:
            raise ScaspExecutionError(completed.stderr.strip() or output or f"s(CASP) failed for query {query}")

        json_start = output.find("{")
        if json_start == -1:
            raise ScaspExecutionError(f"s(CASP) returned non-JSON output for query {query}: {output}")

        payload = json.loads(output[json_start:])
        values: list[str] = []
        for answer in payload.get("answers", []):
            binding = answer.get("bindings", {}).get(variable)
            if binding:
                values.append(self._term_to_string(binding.get("value")))
        return _dedupe(values), payload

    def _term_to_string(self, value: dict[str, Any] | None) -> str:
        if not value:
            return ""
        value_type = value.get("type")
        if value_type == "atom":
            return str(value.get("value"))
        if value_type == "rational":
            denominator = value.get("denominator", 1)
            numerator = value.get("numerator")
            return str(numerator if denominator == 1 else numerator / denominator)
        if value_type == "compound":
            args = ", ".join(self._term_to_string(arg) for arg in value.get("args", []))
            return f"{value.get('functor')}({args})"
        return str(value)

    def _atom(self, value: str) -> str:
        cleaned = value.strip().lower().replace("-", "_").replace(" ", "_")
        if not cleaned.replace("_", "").isalnum():
            raise ValueError(f"Unsafe atom value: {value}")
        return cleaned


def run_policy_safely(facts: FactState, runner: ScaspRunner | None = None) -> PolicyResult:
    """Run s(CASP), converting setup/runtime failures into a user-visible result."""

    if facts.age is not None and facts.age < 18:
        return underage_policy_result(facts)

    active_runner = runner or ScaspRunner()
    try:
        result = active_runner.run(facts)
        if facts.age is not None and facts.age < 18:
            return underage_policy_result(facts)
        return result
    except (ScaspUnavailable, ScaspExecutionError, subprocess.TimeoutExpired) as exc:
        return PolicyResult(error=str(exc))


def underage_policy_result(facts: FactState) -> PolicyResult:
    """Return deterministic adult-scope guidance for applicants under 18."""

    guidance = ["under_18_adult_license_not_available"]
    if facts.age is not None and facts.age < 15:
        guidance.insert(0, "under_15_no_ordinary_driver_license_path")
    return PolicyResult(
        case_type="out_of_scope_under_18",
        service_modes=["not_available_adult_flow"],
        explanations=["under_18_out_of_scope"],
        final_guidance=guidance,
    )


def _dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for value in values:
        if value and value not in seen:
            seen.add(value)
            ordered.append(value)
    return ordered
